[theme]
primaryColor = "#343A73"
backgroundColor = "#F6F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#202C48"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
